# Generated by Django 2.2.6 on 2019-10-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191022_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
